In [1]:
#분석할 텍스트 데이터 불러오기 
import pandas as pd
df = pd.read_csv('/content/StoryImageText.csv', encoding='utf-8')
df[0:57]


No  ...                                          component
0  NaN  ...  안심하고 사용할 수 있는 화장품 성분 EWG 등급을 확인해주세요!\nEWG는 미국 ...
1  NaN  ...  정제수\n다이부틸아디페이트\n프로판다이올\n에칠헥실트리아존\n테레프탈릴리덴 디캠퍼설...
2  NaN  ...                        자외선 차단제 성분도 EWG그린등급만 사용했습니다
3  NaN  ...  테레프탈릴리덴 디캠퍼설포닉애씨드\n에칠헥실트리아존\n디에칠아미노 비스-에칠헥실옥시페...
4  NaN  ...  #1 차이나는 성분\n0:10 DNA S-DNA 피부를 위해 엄선된 원료를 사용하였...
5  NaN  ...                                     함량을 반드시 확인해주세요
6  NaN  ...                  자연유래성분 99% 유기농 성분 64% 비건 포뮬라 100%
7  NaN  ...                                        전성분 100% 비건
8  NaN  ...                                         EWG 등급의 함정
9  NaN  ...                                       향료, 정말 나쁠까요?
10 NaN  ...  함량순으로 보는 전성분 EWG 등급\n징크옥사이드\n알로에베라잎추출물\n(37.75...
11 NaN  ...  프로젝트 코랄의 저자극 비건 선크림 제품 전성분\n전성분 정보\n정제수, 사이클로펜...
12 NaN  ...                           EWG의 색으로도 표시할 수 없는 좋은 성분
13 NaN  ...                                             정제수 0%
14 NaN  ...                                    유기농 알로에 추출물 37%
15 NaN  ...                             선크림 성분, 영양크림보다 좋아야 합니다
16 NaN  ...  REEF SAFE ECTOIN SUN CREAM\n엑토인 10,000ppm 함유\n...
17 NaN  ...  All Green Grade 전성분을 확인하세요!\n뷰티클로 올데이 마일드 선크림 ...
18 NaN  ...  Ectoin 엑토인이란?\nBONAFIDE\nSPF50+ PA++++\nUVAGUV...
19 NaN  ...             엑토인 선크림은 안전한 성분으로 아이들도 안심하고 사용할 수 있어요!
20 NaN  ...  화장품 원료로 쉽게 접하기 어려웠던 기적의 원료\n# 흘러 넘치게!\n10.000P...
21 NaN  ...               무겁지 않은 촉촉한 피부 결을 위해, 수분 성분에 집중하였습니다.
22 NaN  ...  풍부한 미네랄과 수분이 마르지 않는\n하와이 코나 해양심층수\n"왜 하와이 코나 해...
23 NaN  ...  지구 규모의 바다 이야기 HAWAII KONA SEA WATER\n"깨끗하고 영양분...
24 NaN  ...  S\n수분입자 c\n엑토인\nDry Skin\nHealthy Skin\n자외선으로 ...
25 NaN  ...                                  수분 자석으로 불리는 히알루론 
26 NaN  ...                                   피부가 마시는 이온음료 판테놀
27 NaN  ...                    극한의 환경에서 발견한 피부 보습 원료 퉁퉁마디 추출물 
28 NaN  ...                지친 피부의 매끈한 피부 결을 위해 진정 성분에 집중하였습니다.
29 NaN  ...                           피부를 보호해주는 백년초 선인장 열매 추출물
30 NaN  ...                                 피부 진정에는 병풀 추출물, 시카
31 NaN  ...                푸석한 피부에 쫀쫀한 피부 결을 위해 영양 성분에 집중하였습니다
32 NaN  ...                         강인한 생명력의 열정의 붉은 꽃 동백꽃 추출물 
33 NaN  ...  정제수, 징크옥사이드, C12-15알킬벤조에이트, 글리세레스-26, C13-16아이...
34 NaN  ...                            비건 선세럼의 핵심 성분 루이보스잎 추출물
35 NaN  ...  UP\n루이보스잎추출물\n| 100ppm 자외선 노출시 생기는 활성산소로부터 피부를...
36 NaN  ...  자외선 노출시 생기는 활성 산소 로부터 피부를 보호해줍니다.\n피부를 촉촉하게 보습...
37 NaN  ...  이데베논\n비타민C의 4배, 코엔자임Q10 의 10배 활성 산소 보호력으로 알려진 ...
38 NaN  ...  정제수, 에탄올, 페네틸벤조에이트, 디에칠아미노하이드록시벤조일헥실벤조 에이트, 비스...
39 NaN  ...  \n보나파이드의 자존심, 전성분을 꼭 확인하세요!\n꼭 필요한 성분만 하나하나 꼼꼼...
40 NaN  ...  \n*자외선 차단 성분\nSA\n2\n2-3\ndepends on 153\n사이클로...
41 NaN  ...                                                NaN
42 NaN  ...                                                NaN
43 NaN  ...                                                NaN
44 NaN  ...                                                NaN
45 NaN  ...                                                NaN
46 NaN  ...                                                NaN
47 NaN  ...                                                NaN
48 NaN  ...                                                NaN
49 NaN  ...                                                NaN
50 NaN  ...                                                NaN
51 NaN  ...                                                NaN
52 NaN  ...                                                NaN
53 NaN  ...                                                NaN
54 NaN  ...                                                NaN

[55 rows x 5 columns]

In [2]:
#제품 페이지 데이터 가져오기

title = ["FirstPic", "ProductFeature", "Eco-Storytelling"]
main_txt2 = []
result = []

#\n 제거, 리스트 합치기 

for main in title:
  main_txt = df[main].to_list()  
  for v in main_txt:
   if type(v) != str:
     main_txt2.append(str(v).replace('\n', ' '))
   elif type(v) == str:
     main_txt2.append(v.replace('\n', ' '))
  
  result.append(" ".join(main_txt2))
  main_txt2.clear()

print(result)
len(result)

['여러분에게 좋은 선크림의 기준은 무엇인가요? “그냥, 내 피부에 맞으면 그만" “SPF 지수가 높은 거?” “안밀리는? 적당히 흡수 되는 거?" “촉촉한 거?" “백탁 없는 거? 발림성 좋은 거?" 3초 흡수 선에센스 촉촉하고 너무 가볍다. 익숙하지만 볼 때마다 놀라는 이 사진 바다와 피부, 모두를 지키는 저자극 비건 선크림 프로젝트 코랄 Reef Friendly CORAL 자외선과 유해환경 으로부터 당신의 피부는 안녕한가요? nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan', "한눈에보는 CHECK POINT 3초 순삭 흡수력, 매끈 촉촉 사용감 02 자외선 차단은 기본, 스킨케어 기능까지한번에 03 피부를생각하는 마음, 건강한성분과믿을 수있는제조사  선케어 전문브랜드 선티크가 2년 연구 끝에 개발한 SUNTIQUE 가장 혁신적인 무기자차! I'M SAFE FOR BABY & SILVER SF-35 p+++ NON CHEMICAL 100% NATURAL MINERAL FILTER EASY WASHABLE WATER SPLASH EFFECT It is a low-irritation sunscreen without chemical Ingredients that can be used safely for infants and sensitive skin. It reduced stickiness with soft sensation, significantly decreased white residue and moisturizing and cooling effect. 50ml 1.69FL.OZ. 세상에 없던 새로운 무기자차 선크림을 지금 만나보세요. DISCOVER

3

In [3]:
#필요한 패키지 설치 
! apt-get install g++ openjdk-8-jdk python3-dev python3-pip curl
! python3 -m pip install --upgrade pip
! python3 -m pip install konlpy

Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.16).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
g++ set to manually installed.
python3-dev is already the newest version (3.6.7-1~18.04).
python3-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-10-0 cuda-command-line-tools-10-1
  cuda-command-line-tools-11-0 cuda-compiler-10-0 cuda-compiler-10-1
  cuda-compiler-11-0 cuda-cuobjdump-10-0 cuda-cuobjdump-10-1
  cuda-cuobjdump-11-0 cuda-cupti-10-0 cuda-cupti-10-1 cuda-cupti-11-0
  cuda-cupti-dev-11-0 cuda-documentation-10-0 cuda-documentation-10-1
  cuda-documentation-11-0 cuda-documentation-11-1 cuda-gdb-10-0 cuda-gdb-10-1
  cuda-gdb-11-0 cuda-gpu-library-advisor-10-0 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-0 cuda-libraries-10-1 cuda-libraries-11-0
  cuda-memcheck-10-0 cuda-memcheck-1

In [6]:
print(result[0])

여러분에게 좋은 선크림의 기준은 무엇인가요? “그냥, 내 피부에 맞으면 그만" “SPF 지수가 높은 거?” “안밀리는? 적당히 흡수 되는 거?" “촉촉한 거?" “백탁 없는 거? 발림성 좋은 거?" 3초 흡수 선에센스 촉촉하고 너무 가볍다. 익숙하지만 볼 때마다 놀라는 이 사진 바다와 피부, 모두를 지키는 저자극 비건 선크림 프로젝트 코랄 Reef Friendly CORAL 자외선과 유해환경 으로부터 당신의 피부는 안녕한가요? nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan


In [8]:
from konlpy.tag import Okt
import numpy as np
okt = Okt()

#동사/부사/형용사 추출 
clean_verbs = []
clean_nouns = []
clean_adjs = []
clean_all = []
clean_result = []

for j, tag in enumerate(result):
  for word in okt.pos(tag, stem=True):      #어근
    if word[1] in ['Adjective']:
      clean_adjs.append(word[0])
      clean_all.append(word[0]) 
    elif word[1] in ['Verb']:
      clean_verbs.append(word[0])
      clean_all.append(word[0]) 
    elif word[1] in ['Noun']:
      clean_nouns.append(word[0])
      clean_all.append(word[0]) 
  clean_result.append(" ".join(clean_all))
  clean_all.clear()

print(clean_result)
len(clean_result[0])


['여러분 좋다 선크림 기준 무엇 그냥 내 피부 맞다 지수 높다 거 밀리다 적당하다 흡수 되다 거 촉촉하다 거 탁 없다 거 발림 좋다 거 흡수 선 에센스 촉촉하다 가볍다 익숙하다 볼 때 놀라다 이 사진 바다 피부 모두 지키다 자극 비건 선크림 프로젝트 코랄 자외선 유해 환경 당신 피부 안녕하다', '한눈 보다 순삭 흡수 촉촉 용감 자외선 차단 기본 스킨 케어 기능 한번 피부 생각 마음 건강하다 분과 믿다 수 있다 조사 선 케어 전문 브랜드 선 티크 연구 끝 개발 가장 혁신 무기 차 세상 없다 새롭다 무기 차 선크림 지금 만나다 보다 관찰 사람 왜 무기 차 선크림 선호 하다 피부 자극 주지 않다 바르다 즉시 차단 되어다 자주 덧 바르다 필요 간편하다 물리 차단 방식 자외선 차단 제 쉬다 말 하다 피부 보호 막 씌우다 피부 표면 자외선 반사 시키다 물리 차단 제이 미네랄 필터 차단 막 형성 하다 피부 자극 적다 순하다 것 특징 이다 무기 차 유기 차 피부 표면 반사 자외선 튕겨냄 자외선 흡수 후 화학반응 열 배출 무기 차단 막 표피 층 진피 층 표피 층 진피 층 기초 스킨 케어 더욱 까다롭다 고르다 포인트 색조 템 살다 정착 하다 쉬다 않다 카테고리 있다 내 마음 쏙 들다 선크림 왜 없다 발림 성도 좋다 하다 위 베이스 제품 덧 바르다 밀착 좋다 해 거기 다가 아침 바르다 하루 종일 기초 피부 붙다 순하다 자극 적다 하다 굿데이 메이트 선 스크린 하다 와디 서포터 들이다 극찬 비건 워터 선 에센스 만족하다 형 용감 대망 흡수 모두 그대로 담다 사용 하다 수 있다 크게 만들다 가져오다 이르다 통해 프로젝트 코랄 어드밴스드 워터 프루프 무기 차 선 태어나다 프로젝트 코랄 추구 하다 네가지 핵심 가치 환경 고객 편리 제품 퀄리티 지속가능성 환경 우리 모두 위해 더 좋다 환경 제품 만들다 힘 보태 줄다 건강하다 피부 아름답다 환경 모두 생각 하다 당신 위 무기 차 기반 선크림 산호초 유해 물질 철저하다 배제 레시피 전세계 산호초 해변 안전하다 사용 과 밉다 함유 등급 모

162

In [9]:
print(clean_nouns)
len(clean_nouns)

['여러분', '선크림', '기준', '무엇', '그냥', '내', '피부', '지수', '거', '흡수', '거', '거', '탁', '거', '발림', '거', '흡수', '선', '에센스', '볼', '때', '이', '사진', '바다', '피부', '모두', '자극', '비건', '선크림', '프로젝트', '코랄', '자외선', '유해', '환경', '당신', '피부', '한눈', '순삭', '흡수', '촉촉', '용감', '자외선', '차단', '기본', '스킨', '케어', '기능', '한번', '피부', '생각', '마음', '분과', '수', '조사', '선', '케어', '전문', '브랜드', '선', '티크', '연구', '끝', '개발', '가장', '혁신', '무기', '차', '세상', '무기', '차', '선크림', '지금', '관찰', '사람', '왜', '무기', '차', '선크림', '선호', '피부', '자극', '주지', '즉시', '차단', '자주', '덧', '필요', '물리', '차단', '방식', '자외선', '차단', '제', '말', '피부', '보호', '막', '피부', '표면', '자외선', '반사', '물리', '차단', '제이', '미네랄', '필터', '차단', '막', '형성', '피부', '자극', '것', '특징', '무기', '차', '유기', '차', '피부', '표면', '반사', '자외선', '튕겨냄', '자외선', '흡수', '후', '화학반응', '열', '배출', '무기', '차단', '막', '표피', '층', '진피', '층', '표피', '층', '진피', '층', '기초', '스킨', '케어', '더욱', '포인트', '색조', '템', '정착', '카테고리', '내', '마음', '쏙', '선크림', '왜', '발림', '성도', '위', '베이스', '제품', '덧', '밀착', '해', '거기', '다가', '아침', '하루', '종일', '기초', '피부', '자극', '굿

1543

In [15]:
from collections import Counter
Counter(clean_adjs).most_common()

[('있다', 25),
 ('없다', 16),
 ('촉촉하다', 14),
 ('좋다', 11),
 ('가볍다', 9),
 ('순하다', 8),
 ('안전하다', 8),
 ('자연스럽다', 6),
 ('많다', 6),
 ('어떻다', 6),
 ('민감하다', 5),
 ('아름답다', 4),
 ('건강하다', 3),
 ('이다', 3),
 ('강력하다', 3),
 ('건조하다', 3),
 ('같다', 3),
 ('아니다', 3),
 ('의하다', 3),
 ('보송하다', 3),
 ('이러하다', 3),
 ('인하다', 3),
 ('높다', 2),
 ('새롭다', 2),
 ('밉다', 2),
 ('산뜻하다', 2),
 ('확실하다', 2),
 ('정직하다', 2),
 ('원하다', 2),
 ('어렵다', 2),
 ('부드럽다', 2),
 ('착하다', 2),
 ('계시다', 2),
 ('강렬하다', 2),
 ('적당하다', 1),
 ('익숙하다', 1),
 ('안녕하다', 1),
 ('간편하다', 1),
 ('까다롭다', 1),
 ('만족하다', 1),
 ('철저하다', 1),
 ('뜨겁다', 1),
 ('뽀송하다', 1),
 ('따갑다', 1),
 ('다르다', 1),
 ('보송보송하다', 1),
 ('자유롭다', 1),
 ('희다', 1),
 ('편하다', 1),
 ('덥다', 1),
 ('불쾌하다', 1),
 ('찝찝하다', 1),
 ('간단하다', 1),
 ('무겁다', 1),
 ('풍부하다', 1),
 ('이렇다', 1),
 ('힘들다', 1),
 ('편안하다', 1),
 ('부담스럽다', 1),
 ('실패하다', 1),
 ('그렇다', 1),
 ('불편하다', 1),
 ('가능하다', 1),
 ('깨끗하다', 1),
 ('화하다', 1),
 ('심하다', 1),
 ('유사하다', 1),
 ('강화하다', 1),
 ('매끄럽다', 1),
 ('탱탱하다', 1),
 ('좋아하다', 1),
 ('뽀송뽀송하다', 1),
 ('가득하다', 1),
 ('미치다', 

In [11]:
top_nouns = {'피부': 70, '차단': 35, '자외선': 33, '무기': 33, '성분': 19, '발림': 16, '수분':16, '톤업':9, '밀림': 4, '흡수': 12}

from sklearn.feature_extraction.text import TfidfVectorizer 

sunscreen_tfidv = TfidfVectorizer().fit(top_nouns)
sunscreen_tfidv.transform(clean_result).toarray()

array([[0.        , 0.        , 0.25819889, 0.        , 0.        ,
        0.25819889, 0.        , 0.        , 0.77459667, 0.51639778],
       [0.32084001, 0.0418487 , 0.16739479, 0.20924349, 0.22319305,
        0.26504175, 0.36268871, 0.12554609, 0.73932699, 0.09764696],
       [0.41486991, 0.04148699, 0.12446097, 0.16594796, 0.        ,
        0.53933088, 0.37338292, 0.        , 0.58081787, 0.12446097]])

In [12]:
pd.DataFrame(sunscreen_tfidv.transform(clean_result).toarray())

0         1         2  ...         7         8         9
0  0.00000  0.000000  0.258199  ...  0.000000  0.774597  0.516398
1  0.32084  0.041849  0.167395  ...  0.125546  0.739327  0.097647
2  0.41487  0.041487  0.124461  ...  0.000000  0.580818  0.124461

[3 rows x 10 columns]

In [13]:
top_nouns2 = {'환경': 13, '산호초': 8, '산호': 5,  '해양': 7, '위해': 6, '비건': 9, '민감': 6, '메이크업': 6, '효과': 6, '시림': 5, '궁합': 5,  '고민': 4}

from sklearn.feature_extraction.text import TfidfVectorizer 

sunscreen_tfidv = TfidfVectorizer().fit(top_nouns2)
sunscreen_tfidv.transform(clean_result).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.70710678,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        ],
       [0.20272121, 0.33786869, 0.33786869, 0.27029495, 0.47301616,
        0.        , 0.20272121, 0.27029495, 0.20272121, 0.        ,
        0.33786869, 0.40544243],
       [0.07784989, 0.        , 0.07784989, 0.15569979, 0.07784989,
        0.38924947, 0.38924947, 0.07784989, 0.23354968, 0.54494926,
        0.54494926, 0.        ]])

In [14]:
pd.DataFrame(sunscreen_tfidv.transform(clean_result).toarray())

0         1         2   ...        9         10        11
0  0.000000  0.000000  0.000000  ...  0.000000  0.707107  0.000000
1  0.202721  0.337869  0.337869  ...  0.000000  0.337869  0.405442
2  0.077850  0.000000  0.077850  ...  0.544949  0.544949  0.000000

[3 rows x 12 columns]

In [16]:
top_adj = {'촉촉하다': 14, '좋다': 11, '가볍다': 9, '순하다': 8, '안전하다': 8, '자연스럽다': 6, '민감하다': 5, '건강하다': 3, '강력하다': 3, '건조하다': 3, '보송하다': 3, '산뜻하다': 2, '확실하다': 2}

from sklearn.feature_extraction.text import TfidfVectorizer 

sunscreen_tfidv = TfidfVectorizer().fit(top_adj)
sunscreen_tfidv.transform(clean_result).toarray()

array([[0.33333333, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.66666667, 0.66666667, 0.        ],
       [0.35445878, 0.15191091, 0.15191091, 0.15191091, 0.20254787,
        0.15191091, 0.10127394, 0.35445878, 0.20254787, 0.30382181,
        0.30382181, 0.60764362, 0.10127394],
       [0.18898224, 0.        , 0.        , 0.        , 0.18898224,
        0.        , 0.        , 0.18898224, 0.75592895, 0.        ,
        0.56694671, 0.        , 0.        ]])

In [17]:
pd.DataFrame(sunscreen_tfidv.transform(clean_result).toarray())

0         1         2   ...        10        11        12
0  0.333333  0.000000  0.000000  ...  0.666667  0.666667  0.000000
1  0.354459  0.151911  0.151911  ...  0.303822  0.607644  0.101274
2  0.188982  0.000000  0.000000  ...  0.566947  0.000000  0.000000

[3 rows x 13 columns]